### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by rafaelcneves** [khony/ruby-nginx-docker#1]
Gostei muito da tua docker.. Uma sugestão pra deixar ela mais leve e mais versátil.. No lugar de instalar e configurar o postgres e o redis, utiliza `link` do docker pra utilizar as dockers oficiais do postgres e do redis junto a sua.. Juntando isso com o `docker-compose` fica show! Nunca mais vai precisar ficar montando linha de comando pro docker xD

**Comment by fabiomello** [comment]
Opa, show! 
Valeu a dica, comecei a brincar com o docker faz pouco tempo, agora vou tentar mexer com o docker compose entao hehe 

De: "Rafael César Neves" notifications@github.com 
Para: "khony/ruby-nginx-docker" ruby-nginx-docker@noreply.github.com 
Enviadas: Sexta-feira, 8 de julho de 2016 11:18:27 
Assunto: [khony/ruby-nginx-docker] Sugestão (#1) 

Curti altos tua docker.. Uma sugestão pra deixar ela mais leve e mais versátil.. No lugar de instalar e configurar o postgres e o redis, utiliza link do docker pra utilizar as dockers oficiais do postgres e do redis junto a sua.. Juntando isso com o docker-compose fica show! Nunca mais vai precisar ficar montando linha de comando pro docker xD
